from dotenv import load_dotenv
load_dotenv()

from langchain_openai import ChatOpenAI
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

llm1 = ChatOpenAI(model="gpt-3.5-turbo", temperature=0)
llm2 = ChatOpenAI(model="gpt-5-mini", temperature=0)
llm3 = ChatOpenAI(model="gpt-4o-mini", temperature=0)


spec_to_schema = PromptTemplate.from_template(
    """Você é um engenheiro backend sênior.
A partir da especificação de produto abaixo, extraia um JSON schema mínimo com campos e tipos.
Retorne apenas o JSON. Sem comentários.

Escreva todo o código usando blocos de código markdown.

Spec:
{spec}
"""
) | llm1 | StrOutputParser()

schema_to_routes = PromptTemplate.from_template(
    """Você é um desenvolvedor Go sênior.
Com base no JSON schema abaixo, projete rotas REST e esboce handlers idiomáticos em Go para CRUD.
Seja conciso, orientado a produção e mostre trechos de código.

Escreva todo o código usando blocos de código markdown.

Schema JSON:
{schema_json}
"""
) | llm2 | StrOutputParser()

commit_message = PromptTemplate.from_template(
    """Você é um desenvolvedor pragmático.
Escreva uma mensagem de commit convencional em uma única linha resumindo a nova API com base no schema e nas rotas.

Schema:
{schema_json}

Rotas e handlers:
{routes}
"""
) | llm3 | StrOutputParser()


spec_text = """Precisamos de uma API de Produtos.
Campos: id (uuid), name (string, obrigatório), description (string), price (float, > 0), stock (int, >= 0).
Deve suportar listagem com paginação, criação, busca por id, atualização e exclusão.
"""

schema_json = spec_to_schema.invoke({"spec": spec_text})
routes = schema_to_routes.invoke({"schema_json": schema_json})
commit = commit_message.invoke({"schema_json": schema_json, "routes": routes})


result_content = f"""# Prompt Chaining Result

## SCHEMA (Generated by GPT-3.5-turbo)
{schema_json}

## ROUTES & HANDLERS (Go) (Generated by GPT-5-mini)
{routes}

## COMMIT (Generated by GPT-4o-mini)
{commit}

---
**Pipeline Models:**
- Step 1: GPT-3.5-turbo
- Step 2: GPT-5-mini
- Step 3: GPT-4o-mini  

"""

with open("prompt_chaining_result.md", "w", encoding="utf-8") as f:
    f.write(result_content)

print("Resultado salvo em prompt_chaining_result.md")